sudo: required

services:
  - docker

language: shell

before_script:
  - chmod +x .travis/test.sh
  - chmod +x hooks/build

script:
  - readonly IMAGE_NAME='dkorotych/lazybones:travis'
  - hooks/build
  - docker run --rm $IMAGE_NAME help | grep 'Lazybones is a command-line based tool for creating basic software projects from templates.'
  - .travis/test.sh
