sudo: required

services:
  - docker

language: shell

script:
  - readonly TAG='dkorotych/lazybones:travis'
  - docker build -t $TAG .
  - docker run --rm $TAG help | grep 'Lazybones is a command-line based tool for creating basic software projects from templates.'
  - docker run --rm $TAG --entrypoint '/bin/stat -c "%U %G" ../app/' | grep 'lazybones lazybones'
  - docker run --rm $TAG --entrypoint '/bin/stat -c "%U %G" ../.lazybones' | grep 'lazybones lazybones'
  - docker run --rm $TAG --entrypoint '/bin/stat -c "%U %G" ../.lazybones/templates' | grep 'lazybones lazybones'
